services:
  # Base de datos PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: mini_crud_db
    environment:
      POSTGRES_DB: mini_crud_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Aplicación FastAPI
  web:
    build: .
    container_name: mini_crud_api
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/mini_crud_db
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  postgres_data:
